# Generated by Django 4.1.7 on 2023-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.CharField(max_length=15)),
                ('unsubscribed', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='status',
            field=models.BooleanField(choices=[(True, 'Subscribed'), (False, 'Unsubscribed')], default=True, null=True),
        ),
    ]
