# Generated by Django 4.1.7 on 2023-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeune', '0002_statusdescription_alter_subscribers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
